# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SubsetPHP Development Diary
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A type-inferring compiler for a safer and disciplined subset of PHP, based on
  and inspired by HHVM Hack compiler.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  olleharstedt

# Build settings
markdown: kramdown

#highlighter: rouge
